version: 0.1
phases:
  install:
    commands:
      - npm install -g bower
      - npm install -g grunt-cli
      - bower install --allow-root
      - npm install --save-dev @angular/cli@latest
  pre_build:
    commands:
      - pwd
      - tar -cvf dist.tar .
      - mkdir dist
      - tar -xvf dist.tar -C dist
artifacts:
  files:
      - dist/**/*
      - awsscripts/install_nginx.sh
      - awsscripts/start_application.sh
      - awsscripts/stop_application.sh
      - awsscripts/aws_codedeploy_config.sh
      - appspec.yml
base-directory: mifosFrontend     
discard-paths: yes
